# Introduction to DataFrames

In [1]:
import pandas as pd

In [ ]:
df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], columns=["A", "B", "C"], index=["a", "b", "c", "d"])

# df.head()
# df.head(1)        # It is used to see data from top of the matrix.
# df.head(2)
df.head(3)

    A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [17]:
# df.tail()
# df.tail(1)        # It is used to see data from bottom of the matrix.
# df.tail(2)
df.tail(3)

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [22]:
column_info = df.columns
print("Column Info : ", column_info)

index_info = df.index
print("Index Info : ", index_info)

Column Info :  Index(['A', 'B', 'C'], dtype='str')
Index Info :  Index(['a', 'b', 'c'], dtype='str')

In [27]:
df.info()

df.describe()

df.nunique()

df["A"].unique()

<class 'pandas.DataFrame'>
Index: 3 entries, a to c
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

array([1, 4, 7])

In [30]:
df.shape

(3, 3)